### PR TITLE
Run key:generate on install and reset

### LINKED ISSUE #12: app:install to generate key?
Would it be a bad idea to have `app:install` also generate the `APP_KEY`?

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #12

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Forgot to update class authors, but oh well.

**Comment by jbrooksuk** [comment]
@GrahamCampbell can we do this, or add some `before` events we can hook in to? This would simplify the Cachet installation.

**Comment by GrahamCampbell** [comment]
Will ship in 5.0 here.

**Comment by jbrooksuk** [comment]
Whoop!

I'll get our docs updated too.

**Pull request merged**
