### PR TITLE
Update mergeConfigFrom

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Yeh, this needs doing 15 more times too, lol...

**Comment by joecohens** [comment]
Lol I can send you 15 PR if you like hahaha

**Comment by GrahamCampbell** [comment]
I'm doing it now...

**Comment by GrahamCampbell** [comment]
I already updated the flysystem one earlier today.

**Comment by joecohens** [comment]
I know just joking :)

**Pull request merged**
