### PR TITLE
Fire command events for own commands

### PR DESCRIPTION
**Pull request by jbrooksuk**
I need to hook into these commands, but can't as no events are fired.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's the use case please?

**Comment by jbrooksuk** [comment]
Running `key:generate` in Cachet at the start of `app:install`.

**Comment by GrahamCampbell** [comment]
This is something I want to make part of this package itself.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Core/issues/12

**Comment by GrahamCampbell** [comment]
The reset command will also have to regenerate it.

**Comment by GrahamCampbell** [comment]
I've just not had time to do it yet.

**Comment by jbrooksuk** [comment]
So you do want it part of the package? I can make a PR.

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request closed without merging**
